runtime: php83
env: standard

handlers:
  # Favicon
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  # Serve the index.html file
  - url: /index\.php
    static_files: index.php
    upload: index\.php

  # Serve PHP, HTML, and image files
  - url: /(.*\.(php|html|jpg|jpeg|png|gif|bmp|webp))$
    script: auto

  # Serve static files from the /static directory
  - url: /static/(.*)
    static_files: static/\1
    upload: static/.*

  # Catch-all for other scripts or files
  - url: /.*
    script: auto
