runtime: php83
service: default
env: standard

handlers:
  # Serve static files (CSS, JS, images) from a "static" directory
  - url: /static
    static_dir: static

  # Serve the main index.php file for the root URL
  - url: /
    script: auto

  # Serve PHP files in the templates directory
  - url: /templates
    script: auto

  # Catch-all handler for all other requests
  - url: /.*
    script: auto