runtime: php83
env: standard

handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico
  - url: /index\.html
    static_files: index.html
    upload: index\.html
  - url: /(.+\.(php|html|jpg))$
    script: \1
  - url: /static/(.*)
    static_files: static/\1
    upload: static/.*
  - url: .*/(.*\.(php|html|jpg))$
    script: \1
  - url: .*
    script: auto